import { useState } from 'react'
import { Bot, CheckCircle2, Play, RefreshCw } from 'lucide-react'

import { getApiErrorMessage } from '@/services/client'
import { runAutomation } from '@/services/automation'
import type { AutomationResult } from '@/types/api'

export function AutomationPage() {
  const [result, setResult] = useState<AutomationResult | null>(null); const [error, setError] = useState<string | null>(null); const [running, setRunning] = useState(false)
  async function run() { if (running) return; setRunning(true); setError(null); try { setResult(await runAutomation()) } catch (caught) { setError(getApiErrorMessage(caught)) } finally { setRunning(false) } }
  return <div className="mx-auto max-w-4xl space-y-6"><section className="rounded-3xl bg-gradient-to-br from-violet-700 to-indigo-700 p-7 text-white shadow-xl shadow-violet-100 sm:p-10"><div className="grid size-12 place-items-center rounded-2xl bg-white/15"><Bot className="size-6" /></div><h2 className="mt-6 text-3xl font-bold">Keep your knowledge current.</h2><p className="mt-3 max-w-2xl text-violet-100">Run a manual refresh to detect new events, regenerate affected knowledge nodes, synchronize vectors, and create update notifications.</p><button onClick={() => void run()} disabled={running} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-violet-700 transition hover:bg-violet-50 disabled:opacity-60">{running ? <RefreshCw className="size-4 animate-spin" /> : <Play className="size-4 fill-current" />}{running ? 'Refreshing knowledge…' : 'Run automation'}</button></section>{error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800">{error}</div>}{result && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-3"><CheckCircle2 className="size-6 text-emerald-600" /><div><h3 className="font-bold text-slate-950">{result.status}</h3><p className="mt-1 text-sm text-slate-500">The refresh workflow completed successfully.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{[['Events detected', result.events_detected], ['Features updated', result.updated_features.length], ['Vectors updated', result.vectors_updated], ['Notifications', result.notifications_created]].map(([label, value]) => <div className="rounded-xl bg-slate-50 p-4" key={label as string}><p className="text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs font-medium text-slate-500">{label}</p></div>)}</div>{result.updated_features.length > 0 && <p className="mt-5 text-sm text-slate-600">Updated features: <span className="font-medium text-slate-800">{result.updated_features.join(', ')}</span></p>}</section>}</div>
}
